server:
  mode: local
  gin_mode: debug
mysql:
  user: root
  pass: root
  host: localhost
  port: 3306
  name: video
  parse_time: true
  charset: utf8mb4
  loc: UTC
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600
log:
  log_level: debug
  file_path: storages/logs/video.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: localhost
  port: 6379
  password:
  database: 0
consul:
  address: localhost:8500
  scheme: http
  data_center: dc1
  token:
security:
  jwt_access_secret: 8RgPPwhw6BKHRHT68vfpZpTnpWEJqRV3lUQd4QJlrs12RNiLFtk1QpvGQoB1
  jwt_refresh_secret: ROSyJWWHgSejTAEIemaSrLT59Evc2M9AUtp4O4sVHGpIFS9rLGGEx0GPAPiV
  jwt_access_expiration: 15m
  jwt_refresh_expiration: 24h
s3:
  bucket: youtube-golang
  region: ap-southeast-1
opentelemetry:
  endpoint: localhost:4317
scylla:
  host: localhost
  port: 9042
  username: cassandra
  password: cassandra
  keyspace: video
