apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway-deployment
    labels:
        app: gateway
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    replicas: 1
    selector:
        matchLabels:
            app: gateway
    template:
        metadata:
            labels:
                app: gateway
        spec:
            automountServiceAccountToken: false
            containers:
                - name: gateway
                  image: ${HARBOR_HOST}/gateway:${TAG}
                  imagePullPolicy: Always
                  command: ["./gateway"]
                  env:
                      - name: GO_ENV
                        value: "production"