apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
    labels:
        app: worker
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    replicas: 1
    selector:
        matchLabels:
            app: worker
    template:
        metadata:
            labels:
                app: worker
        spec:
            automountServiceAccountToken: false
            containers:
                - name: worker
                  image: ${HARBOR_HOST}/worker:${TAG}
                  imagePullPolicy: Always
                  command: ["./worker"]
                  env:
                      - name: GO_ENV
                        value: "production"