server:
  port: 8080
  mode: development
# mysql:
#   host: mysql
#   port: 3306
#   user: root
#   pass: root
#   name: veeflow
#   max_idle_conns: 10
#   max_open_conns: 100
#   max_lifetime: 3600
log:
  log_level: debug
  file_path: storages/logs/gateway.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: redis
  port: 6379
  password:
  database: 0
consul:
  address: consul:8500
  scheme: http
  data_center: dc1
  token:
security:
  jwt_access_secret: 8RgPPwhw6BKHRHT68vfpZpTnpWEJqRV3lUQd4QJlrs12RNiLFtk1QpvGQoB1
  jwt_refresh_secret: ROSyJWWHgSejTAEIemaSrLT59Evc2M9AUtp4O4sVHGpIFS9rLGGEx0GPAPiV
  jwt_access_expiration: 15m
  jwt_refresh_expiration: 24h
