apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: consul
data:
  consul.hcl: |
    datacenter = "dc1"
    data_dir = "/consul/data"
    server = true
    bootstrap_expect = 1
    ui_config {
      enabled = true
    }
    bind_addr = "0.0.0.0"
    client_addr = "0.0.0.0"


apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
spec:
  selector:
    app: consul
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      name: http
    - port: 8600
      targetPort: 8600
      protocol: UDP
      name: dns
  type: ClusterIP


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: consul
spec:
  selector:
    matchLabels:
      app: consul
  serviceName: "consul"
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:1.16.2
          args:
            - "agent"
            - "-config-file=/consul/configmap/consul.hcl"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /consul/configmap
            - name: data
              mountPath: /consul/data
      volumes:
        - name: config
          configMap:
            name: consul-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path

apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  namespace: consul
spec:
  selector:
    app: consul
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30085
      protocol: TCP
      name: http
  type: NodePort