replicaCount: 1

zookeeper:
  enabled: false

externalZookeeper:
  servers:
    - zookeeper-headless.kafka.svc.cluster.local

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

listeners:
  client:
    protocol: PLAINTEXT
