global:
  enabled: true

server:
  enabled: true
  ha:
    enabled: true
    replicas: 1
  dataStorage:
    enabled: true
    storageClass: "standard" 
    accessMode: ReadWriteOnce
    size: 8Gi

  standalone:
    enabled: false

  extraEnvironmentVars:
    VAULT_LOG_LEVEL: "info"

  volumes:
    - name: vault-config
      configMap:
        name: vault-config

  volumeMounts:
    - name: vault-config
      mountPath: /vault/userconfig/vault-config
      readOnly: true

  config: |
    ui = true

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "consul" {
      address = "my-consul-consul-server:8500"
      path    = "vault/"
    }

    service_registration "kubernetes" {}
