name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
    
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            gateway:
              - 'gateway/**'
            user:
              - 'user/**'
            video:
              - 'video/**'

      - name: Determine projects to process
        id: projects
        run: |
          projects=()
          if [ "${{ steps.filter.outputs.gateway }}" = "true" ]; then
            projects+=("gateway")
          fi
          if [ "${{ steps.filter.outputs.user }}" = "true" ]; then
            projects+=("user")
          fi
          if [ "${{ steps.filter.outputs.video }}" = "true" ]; then
            projects+=("video")
          fi
          echo "Projects to process: ${projects[@]}"
          echo "projects=${projects[*]}" >> $GITHUB_OUTPUT

      - name: Test changed projects
        run: |
          IFS=' ' read -r -a projects <<< "${{ steps.projects.outputs.projects }}"
          for project in "${projects[@]}"; do
            echo "Testing project: $project"
            make test-$project
          done

      - name: Build changed projects
        run: |
          IFS=' ' read -r -a projects <<< "${{ steps.projects.outputs.projects }}"
          for project in "${projects[@]}"; do
            echo "Building project: $project"
            make build-$project
          done

      - name: Docker Build changed projects
        run: |
          IFS=' ' read -r -a projects <<< "${{ steps.projects.outputs.projects }}"
          for project in "${projects[@]}"; do
            echo "Docker building project: $project"
            docker-compose build $project
          done

      - name: Docker Push changed projects to docker registry
        run: |
          echo 'Do it in the future'
